function buttonClick()
    {
      document.querySelector("h35").innerHTML = "Flour - 400 g + for sprinkling on a baking sheet" 
      document.querySelector("h36").innerHTML = "Salt - 1 tsp"
      document.querySelector("h8").innerHTML = "Water - 200 ml"
      document.querySelector("h7").innerHTML = "Baking powder - 1 teaspoon"
      document.querySelector("h9").innerHTML = "Vegetable oil - 5 teaspoons"
      document.querySelector("h12").innerHTML = "Sugar - 0.5 tsp"
      document.querySelector("h11").innerHTML = "Sausage"
      document.querySelector("h10").innerHTML = "Hard cheese"
      document.querySelector("h13").innerHTML = "Tomato sauce - 2 tbsp. spoons"
      document.querySelector("h17").innerHTML = "Onions - 1 pc"
      document.querySelector("h15").innerHTML = "Sweet pepper - 1 pc"
      document.querySelector("h16").innerHTML = "Oregano - 0.5 tsp"
      document.querySelector("h18").innerHTML = "Prepare all the necessary ingredients for making yeast pizza with sausage, tomato and cheese."
      document.querySelector("h19").innerHTML = "Cooking quick pizza dough. To do this, mix the flour with salt and baking powder. Pour in oil and water"
      document.querySelector("h20").innerHTML = "Knead for 5-7 minutes, the dough is soft and slightly sticks to your hands. Immediately divide into two equal parts - you get two pizzas"
      document.querySelector("h21").innerHTML = "We spread on a baking sheet greased with oil and sprinkled with flour (I have a bottom from a detachable shape with a diameter of 24 cm), align and form small sides"
      document.querySelector("h22").innerHTML = "Cooking the filling for pizza. To do this, cut the onion rings, sweet pepper - thin straws. Cut the sausage into circles, and three cheese on a coarse grater"
      document.querySelector("h23").innerHTML = "Lubricate the dough with thick tomato sauce (we have homemade), sprinkle with a pinch of oregano and spread the filling. Sprinkle with cheese on top"
      document.querySelector("h24").innerHTML = "Bake fast pizza from yeast-free dough in a preheated oven for 15-20 minutes at a temperature of 230 degrees. Watch out for pizza, everyone has different ovens."
      document.querySelector("h25").innerHTML = "Cut red sweet pepper into small cubes and spread into slices of sausage and between them"
      document.querySelector("h27").innerHTML = "Then, in a chaotic manner, place the pieces of butter on the pizza"
      document.querySelector("h26").innerHTML = "Cut the tomato into thin slices, while cutting the stem. Spread the tomato slices on the pizza."
      document.querySelector("h28").innerHTML = "Serve pizza with sausage, tomatoes and cheese with heat, immediately after cooking."
      document.querySelector("h29").innerHTML = "Bon Appetit!"

      }
        function buttonClick2()
    {
      document.querySelector("h35").innerHTML = "Flour - 150 g" 
      document.querySelector("h36").innerHTML = "Dry yeast - 3 g"
      document.querySelector("h7").innerHTML = "Water - 80 ml"
      document.querySelector("h8").innerHTML = "Sunflower or olive oil - 1 tbsp. a spoon"
      document.querySelector("h9").innerHTML = "Salt - 0.25 teaspoons"
      document.querySelector("h10").innerHTML = "Sugar - 0.5 tsp"
      document.querySelector("h11").innerHTML = "Hard cheese - 100 g"
      document.querySelector("h12").innerHTML = "Sausage - 100 g"
      document.querySelector("h13").innerHTML = "Tomato (large) - 1 pc."
      document.querySelector("h17").innerHTML = "Ketchup - 2 tbsp. spoons"
      document.querySelector("h15").innerHTML = "Sweet red pepper - 60 g"
      document.querySelector("h16").innerHTML = "Butter - 25 g"
      document.querySelector("h18").innerHTML = "Make pizza yeast dough. Pour warm boiled water into a bowl, add sugar and dry yeast. Shuffle"
      document.querySelector("h19").innerHTML = "Then pour in the sunflower, and preferably olive oil. Add salt, mix again."
      document.querySelector("h20").innerHTML = "Pouring flour in parts, knead the dough. Gather the dough in a bowl, cover the bowl with a clean kitchen towel and place in a warm place for 40 minutes."
      document.querySelector("h21").innerHTML = "Match the yeast pizza dough."
      document.querySelector("h22").innerHTML = "On a sheet of parchment powder sprinkled with flour, roll the dough into a thin circle with a diameter of about 25 cm."
      document.querySelector("h23").innerHTML = "Lubricate the pizza base with ketchup or any other pizza sauce"
      document.querySelector("h24").innerHTML = "Peel the sausage from the shell, cut into thin slices or slices. Put the sausage on the dough, greased with sauce."
      document.querySelector("h25").innerHTML = "Cut red sweet pepper into small cubes and spread into slices of sausage and between them"
      document.querySelector("h26").innerHTML = "Then, in a chaotic manner, place the pieces of butter on the pizza"
      document.querySelector("h27").innerHTML = "Cut the tomato into thin slices, while cutting the stem. Spread the tomato slices on the pizza."
      document.querySelector("h28").innerHTML = "Grate hard cheese on a coarse grater, sprinkle them with the filling of pizza"
      document.querySelector("h29").innerHTML = "Bake homemade pizza in an oven preheated to 200 degrees for about 15 minutes"

      }